Moex\CoreBundle\Entity\MeOrders:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeOrdersRepository
  table: me_orders
  relations:
    MeUsers:
      class: MeUsers
      local: userId
      foreign: id
      type: many
      foreignType: one
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: IDENTITY
    userId:
      type: bigint
      nullable: false
      column: user_id
    orderFrom:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_from
    orderTo:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_to
    orderInfo:
      type: text
      nullable: false
      column: order_info
    phone:
      type: string
      length: 250
      fixed: false
      nullable: false
    price:
      type: string
      length: 250
      fixed: false
      nullable: false
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
      column: created_at 
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
      column: updated_at 
  lifecycleCallbacks: {  }
