parameters:
  moex.version: V1.0
  moex.pagesize.default: 10
  medrivers_type.class: Moex\CoreBundle\Form\MeDriversType
services:
    core.form.medrivers_type:
        class: %medrivers_type.class%
        arguments: [@translator]
